import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;


import { ToastContainer } from 'react-toastify';

const poppins = Poppins({
  subsets: ['latin'], // Specify required subsets
  display: 'swap', // Control font loading behavior
  variable: '--font-poppins', // Define a CSS variable for the font
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Gopaddi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
