import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { ToastContainer } from 'react-toastify';
import LoadingScreen from "@/components/LoadingScreen";

const poppins = Poppins({
  subsets: ['latin'], 
  display: 'swap', 
  variable: '--font-poppins', 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});


export const metadata: Metadata = {
  title: "Gopaddi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
        <ToastContainer />
        <LoadingScreen/>
      </body>
    </html>
  );
}